<?php
$this->headLink()
    ->prependStylesheet('css/style.css')
    ->prependStylesheet('css/fonts.css')
    ->prependStylesheet('css/bootstrap.css')
    ->prependStylesheet('https://fonts.googleapis.com/css?family=Roboto+Mono:300,400,500,700');

$this->inlineScript()
    ->prependFile('js/script.js')
    ->prependFile('js/core.min.js');
?>
<!DOCTYPE html>
<html lang="ru" class="wide wow-animation">
<head>
    <meta name="format-detection" content="telephone=no">
    <meta name="viewport" content="width=device-width height=device-height initial-scale=1.0 maximum-scale=1.0 user-scalable=0">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta charset="utf-8">
    <link rel="shortcut icon" href="images/favicon.ico" />
    <?=$this->headTitle('zend-expressive')->setSeparator(' - ')->setAutoEscape(false)?>
    <?=$this->headMeta()?>
    <?=$this->headLink()?>
    <!--[if lt IE 10]>
    <div style="background: #212121; padding: 10px 0; box-shadow: 3px 3px 5px 0 rgba(0,0,0,.3); clear: both; text-align:center; position: relative; z-index:1;">
        <a href="http://windows.microsoft.com/en-US/internet-explorer/">
            <img src="images/ie8-panel/warning_bar_0000_us.jpg" border="0" height="42" width="820" alt="Вам необходимо обновить браузер на более новый">
        </a>
    </div>
    <script src="js/html5shiv.min.js"></script>
    <![endif]-->
</head>
<body class="app">
    <!-- Page Header-->
    <header class="section page-header">
        <!-- RD Navbar-->
        <div class="rd-navbar-wrap rd-navbar-absolute">
            <nav class="rd-navbar rd-navbar-thin" data-layout="rd-navbar-fixed" data-sm-layout="rd-navbar-fixed" data-md-layout="rd-navbar-fixed" data-md-device-layout="rd-navbar-fixed" data-lg-layout="rd-navbar-static" data-lg-device-layout="rd-navbar-fixed" data-xl-layout="rd-navbar-static" data-xl-device-layout="rd-navbar-fixed" data-xxl-layout="rd-navbar-static" data-xxl-device-layout="rd-navbar-static" data-lg-stick-up-offset="46px" data-xl-stick-up-offset="46px" data-xxl-stick-up-offset="46px" data-lg-stick-up="true" data-xl-stick-up="true" data-xxl-stick-up="true">
                <div class="rd-navbar-main-outer">
                    <button class="rd-navbar-collapse-toggle rd-navbar-fixed-element-2" data-rd-navbar-toggle=".rd-navbar-collapse"><span></span></button>
                    <div class="rd-navbar-main">
                        <!-- RD Navbar Panel-->
                        <div class="rd-navbar-panel">
                            <!-- RD Navbar Toggle-->
                            <button class="rd-navbar-toggle" data-rd-navbar-toggle="#rd-navbar-nav-wrap-1, #rd-navbar-hidden-1"><span></span></button>
                            <!-- RD Navbar Brand--><a class="rd-navbar-brand" href="index.html"><img src="images/logo-default-169x24.png" alt="" width="169" height="24" srcset="images/logo-default-324x45.png 2x"/></a>
                            <div class="rd-navbar-block" id="rd-navbar-hidden-1">
                                <div class="rd-navbar-collapse">
                                    <ul class="list-inline-bordered rd-navbar-list">
                                        <li><span class="icon mdi mdi-comment-text-outline"></span><a href="contacts.html">Contact us</a></li>
                                        <li><span class="icon mdi mdi-cellphone-android"></span><a href="tel:#">+1-800-456-6743</a></li>
                                    </ul>
                                </div>
                                <button class="rd-navbar-search-toggle" data-rd-navbar-toggle="#rd-navbar-search-1"><span></span></button>
                            </div>
                        </div>
                        <!-- RD Navbar Search-->
                        <div class="rd-navbar-search" id="rd-navbar-search-1">
                            <form class="rd-search" action="search-results.html" data-search-live="rd-search-results-live-1" method="GET">
                                <div class="form-wrap">
                                    <label class="form-label" for="rd-navbar-search-form-input-1">Search...</label>
                                    <input class="form-input rd-navbar-search-form-input" id="rd-navbar-search-form-input-1" type="text" name="s" autocomplete="off">
                                    <div class="rd-search-results-live" id="rd-search-results-live-1"></div>
                                </div>
                                <button class="rd-search-form-submit fa-search" type="submit"></button>
                            </form>
                        </div>
                        <div class="rd-navbar-nav-wrap" id="rd-navbar-nav-wrap-1">
                            <!-- RD Navbar Brand--><a class="rd-navbar-brand" href="index.html"><img src="images/logo-default-169x24.png" alt="" width="169" height="24" srcset="images/logo-default-324x45.png 2x"/></a>
                            <!-- RD Navbar Nav-->
                            <ul class="rd-navbar-nav">
                                <li class="rd-nav-item active"><a class="rd-nav-link" href="index.html">Home</a>
                                </li>
                                <li class="rd-nav-item"><a class="rd-nav-link" href="services.html">Services</a>
                                </li>
                                <li class="rd-nav-item"><a class="rd-nav-link" href="#">Blog</a>
                                    <!-- RD Navbar Dropdown-->
                                    <ul class="rd-menu rd-navbar-dropdown">
                                        <li class="rd-dropdown-item"><a class="rd-dropdown-link" href="sidebar-blog.html">Sidebar Blog</a></li>
                                        <li class="rd-dropdown-item"><a class="rd-dropdown-link" href="single-blog-post.html">Single Blog Post</a></li>
                                    </ul>
                                </li>
                                <li class="rd-nav-item"><a class="rd-nav-link" href="#">Portfolio</a>
                                    <!-- RD Navbar Dropdown-->
                                    <ul class="rd-menu rd-navbar-dropdown">
                                        <li class="rd-dropdown-item"><a class="rd-dropdown-link" href="grid-gallery.html">Grid Gallery</a></li>
                                        <li class="rd-dropdown-item"><a class="rd-dropdown-link" href="single-project.html">Single Project</a></li>
                                    </ul>
                                </li>
                                <li class="rd-nav-item"><a class="rd-nav-link" href="#">Pages</a>
                                    <!-- RD Navbar Megamenu-->
                                    <ul class="rd-menu rd-navbar-megamenu">
                                        <li class="rd-megamenu-item">
                                            <div class="banner" style="background-image: url(images/megamenu-banner-1-570x368.jpg);">
                                                <a class='button button-sm button-primary button-winona' href='#'>Buy Theme</a>
                                            </div>
                                        </li>
                                        <li class="rd-megamenu-item">
                                            <ul class="rd-megamenu-list">
                                                <li class="rd-megamenu-list-item"><a class="rd-megamenu-list-link" href="404-page.html">404 Page</a></li>
                                                <li class="rd-megamenu-list-item"><a class="rd-megamenu-list-link" href="503-page.html">503 Page</a></li>
                                                <li class="rd-megamenu-list-item"><a class="rd-megamenu-list-link" href="coming-soon.html">Coming Soon</a></li>
                                                <li class="rd-megamenu-list-item"><a class="rd-megamenu-list-link" href="under-construction.html">Under Construction</a></li>
                                                <li class="rd-megamenu-list-item"><a class="rd-megamenu-list-link" href="about-me.html">About Me</a></li>
                                                <li class="rd-megamenu-list-item"><a class="rd-megamenu-list-link" href="grid-gallery.html">Grid Gallery</a></li>
                                            </ul>
                                        </li>
                                        <li class="rd-megamenu-item">
                                            <ul class="rd-megamenu-list">
                                                <li class="rd-megamenu-list-item"><a class="rd-megamenu-list-link" href="careers.html">Careers</a></li>
                                                <li class="rd-megamenu-list-item"><a class="rd-megamenu-list-link" href="search-results.html">Search results</a></li>
                                                <li class="rd-megamenu-list-item"><a class="rd-megamenu-list-link" href="services.html">Services</a></li>
                                                <li class="rd-megamenu-list-item"><a class="rd-megamenu-list-link" href="single-service.html">Single Service</a></li>
                                                <li class="rd-megamenu-list-item"><a class="rd-megamenu-list-link" href="single-job.html">Single Job</a></li>
                                                <li class="rd-megamenu-list-item"><a class="rd-megamenu-list-link" href="privacy-policy.html">Privacy policy</a></li>
                                            </ul>
                                        </li>
                                    </ul>
                                </li>
                                <li class="rd-nav-item"><a class="rd-nav-link" href="contacts.html">Contacts</a>
                                </li>
                            </ul>
                        </div>
                    </div>
                </div>
            </nav>
        </div>
    </header>

    <?=$this->content?>

    <!-- Page Footer-->
    <footer class="section footer-minimal bg-primary-darken">
        <div class="container">
            <div class="footer-minimal-inner"><a class="brand" href="index.html"><img src="images/logo-light-167x23.png" alt="" width="167" height="23" srcset="images/logo-light-324x45.png 2x"/></a>
                <!-- Rights-->
                <p class="rights"><span>&copy;&nbsp;</span><span class="copyright-year"></span><span>&nbsp;</span><span>All Rights Reserved.</span><span>&nbsp;</span><br class="d-sm-none"/><a href="#">Terms of Use</a><span> and</span><span>&nbsp;</span><a href="privacy-policy.html">Privacy Policy</a></p>
            </div>
        </div>
    </footer>

<!--    <div class="preloader">-->
<!--        <div class="preloader-logo"><img src="images/logo-default-169x24.png" alt="" width="169" height="24" srcset="images/logo-default-324x45.png 2x"/>-->
<!--        </div>-->
<!--        <div class="preloader-body">-->
<!--            <div id="loadingProgressG">-->
<!--                <div class="loadingProgressG" id="loadingProgressG_1"></div>-->
<!--            </div>-->
<!--        </div>-->
<!--    </div>-->

    <!-- Global Mailform Output-->
    <div class="snackbars" id="form-output-global"></div>

    <?=$this->inlineScript()?>
</body>
</html>
